<div style=" font-size:14px;  ">
	<div style="padding: 10px 0px;">
		<!--
		<h1 style="padding: 0px 15px; margin: 0px; overflow: hidden; height: 48px;">
			<a title="$webname$用户中心" href="http://$host$/" target="_blank" swaped="true">
			<img style="border-width: 0px; padding: 0px; margin: 0px;" alt="$webname$用户中心" src="http://$host$/data/images/base/email_logo.png" height="48" width="208"></a>
		</h1>
		-->
		
		<div style="padding: 2px 20px 30px;">
			<p>亲爱的 <span style="color: rgb(196, 0, 0);">$username$</span>,您好！</p>
			<p>感谢您使用$webname$网络信息平台，附件是您的借款协议书。请注意查收</p>
			<p>感谢您光临$webname$用户中心，我们的宗旨：做中国最安全，用户最喜欢，社会责任心最强的网络借贷平台！  <br>现在就登录吧!
			<a title="点击登录$webname$用户中心" href="$host$" target="_blank" swaped="true">$host$</a> 
			</p>
			<p style="text-align: right;"><br>$webname$用户中心 敬启</p>
			<p><br>此为自动发送邮件，请勿直接回复！如您有任何疑问，请点击<a title="点击联系我们" style="color: rgb(15, 136, 221);" href="$host$/article/list.html?nid=lxwm" target="_blank" >联系我们</a></p>
		</div>
	</div>
</div>