<div style=" font-size:14px;  ">
	<div style="padding: 10px 0px;">
		<!--
		<h1 style="padding: 0px 15px; margin: 0px; overflow: hidden; height: 48px;">
			<a title="$webname$用户中心" href="http://$host$/" target="_blank" swaped="true">
			<img style="border-width: 0px; padding: 0px; margin: 0px;" alt="$webname$用户中心" src="http://$host$/data/images/base/email_logo.png" height="48" width="208"></a>
		</h1>
		-->
		
		<div style="padding: 2px 20px 30px;">
			<p>尊敬的用户 <span style="color: rgb(196, 0, 0);">$username$</span>:</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;您好!</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;您的【$borrowname$】借款现已逾期【$latedays$】天，造成逾期利息【$lateInterest$】元</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;请尽快还款，谢谢！</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;感谢您对我们的支持与关注。</p>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<p>你可以登录【$webname$】访问我的账户"-"我的投资"-"还款明细帐"来查看该笔借款的还款明细计划！</p> 
			
			<p style="text-align: right;"><br>$webname$</p>
			<p><br>此为系统发送邮件，请勿直接回复！如有疑问，请您登录<a title="$webname$" style="color: rgb(15, 136, 221);" href="$host$" target="_blank" >$webname$</a>  ，或致电$fuwutel$。</p>
		</div>
	</div>
</div>